# tasks/main.yml

- name: Keys | Create dir /root/.ssh
  file: path=/root/.ssh state=directory mode=0755

- name: Keys | Ensure github.com is a known host
  lineinfile:
    dest: /root/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

- name: Keys | Load secret keys
  include_vars: {{ key_file }}
  no_log: true

- name: Keys | Copy secret keys
  copy:
    dest="{{ item.key }}"
    content="{{ item.value.content }}"
    owner="{{ item.value.owner }}"
    group="{{ item.value.group }}"
    mode="{{ item.value.mode }}"
  with_dict: private_ssl_key
  no_log: true
